ForumQA/forum_qa/forum_qa/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('', include('question.urls')),
    path('answer/', include('answer.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ForumQA/forum_qa/user/urls.py
from django.urls import path
from . import views
from .views import UserDetailView, UserDeleteView


urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user-delete'),
]

ForumQA/forum_qa/answer/models.py
from django.db import models
from django.contrib.auth.models import User
from question.models import Question
from django.urls import reverse


class Answer(models.Model):
    content = models.TextField(verbose_name="Resposta")
    # Date posted is automatically set to time when it is posted
    date_posted = models.DateTimeField(auto_now_add=True)
    # When user is deleted, answer is also deleted
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # When question is deleted, answer is also deleted
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # Number of upvotes and downvotes are initially zero
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('question-detail', kwargs={'pk': self.question.pk})

    def __str__(self):
        if len(self.content) > 20:
            return self.content[:20] + "[...]"
        return self.content

ForumQA/forum_qa/question/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Question(models.Model):
    title = models.CharField(max_length=100, verbose_name="Descrição breve")
    content = models.TextField(verbose_name="Conteúdo da pergunta")
    # Date posted is automatically set to time when it is posted
    date_posted = models.DateTimeField(auto_now_add=True)
    # When user is deleted, question is also deleted
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # Number of upvotes and downvotes are initially zero
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('question-detail', kwargs={'pk': self.pk})

ForumQA/forum_qa/user/models.py
from django.db import models
from django.contrib.auth.models import User
#from PIL import Image


class Profile(models.Model):
    description = models.TextField(null=True, blank=True,
                                   default="", verbose_name="Breve descrição")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        default='default.png', upload_to='profile_pics', verbose_name="Imagem de perfil")

    def __str__(self):
        return f'{self.user.username} Profile'

    # Shrink image size. Will not be used in S3
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

ForumQA/forum_qa/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'image']

ForumQA/forum_qa/user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic import DetailView, DeleteView
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Conta criada com sucesso!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Perfil editado com sucesso')
            return redirect('/')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'user/profile.html', context)


class UserDetailView(DetailView):
    model = Profile


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'user/user_confirm_delete.html'
    success_url = '/'
    model = User

    def test_func(self):
        return self.request.user == self.get_object()

ForumQA/forum_qa/user/templates/user/login.html
{% extends 'question/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Entre em sua conta</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Entrar</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Não possui uma conta? <a class="ml-2" href="{% url 'register' %}">Registre-se agora!</a>
            </small>
        </div>
    </div>
{% endblock content %}

ForumQA/forum_qa/user/templates/user/logout.html
{% extends 'question/base.html' %}
{% block content %}
<h2>Você saiu da sua conta</h2>
<div class="border-top pt-3">
    <a href="{% url 'login' %}">Entrar</a>
</div>
{% endblock content %}

ForumQA/forum_qa/user/templates/user/profile.html
{% extends 'question/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Informações do perfil</legend>
      {{ u_form|crispy }}
      {{ p_form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Salvar mudanças</button>
    </div>
  </form>
</div>
{% endblock content %}

ForumQA/forum_qa/user/templates/user/profile_detail.html
{% extends 'question/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ object.user.profile.image.url }}" />
    <div class="media-body">
      <h2 class="account-heading">{{ object.user.username }}</h2>
      <p class="text-secondary">{{ object.user.get_full_name }} - {{ object.user.email }}</p>
      <p class="article-content">{{ object.description }}</p>
    </div>
  </div>
</div>

{% if object.user == user %}
<div>
  <a class="btn btn-outline-info" href="{% url 'profile' %}">Editar Perfil</a>
  <a class="btn btn-outline-danger" href="{% url 'user-delete' user.id %}">Excluir Perfil</a>
</div>
{% endif %}
<div style="margin-top: 20px">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="question-tab" data-toggle="tab" href="#question" role="tab"
        aria-controls="question" aria-selected="true">Perguntas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="answer-tab" data-toggle="tab" href="#answer" role="tab" aria-controls="answer"
        aria-selected="false">Respostas</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="question" role="tabpanel" aria-labelledby="question-tab">
      {% if object.user.question_set.all %}
      {% for question in object.user.question_set.all reversed %}
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <small class="text-muted">{{ question.date_posted|date:"F d, Y" }}</small>
          </div>
          <h4>
            <a class="article-title" href="{% url 'question-detail' question.id %}">{{ question.title }}</a>
          </h4>
        </div>
      </article>
      {% endfor %}
      {% else %}
      <div class="content-section">
        <p class="article-content">Nenhuma pergunta postada.</p>
      </div>
      {% endif %}

    </div>
    <div class="tab-pane fade" id="answer" role="tabpanel" aria-labelledby="answer-tab">
      {% if object.user.answer_set.all %}
      {% for answer in object.user.answer_set.all reversed %}
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <small class="text-muted">{{ answer.date_posted|date:"F d, Y" }}</small>
          </div>
          <h4>
            <a class="article-title"
              href="{% url 'question-detail' answer.question.id %}">{{ answer.question.title }}</a>
          </h4>
          <p class="article-content">{{ answer }}</p>
        </div>
      </article>
      {% endfor %}
      {% else %}
      <div class="content-section">
        <p class="article-content">Nenhuma resposta postada.</p>
      </div>
      {% endif %}
    </div>
  </div>

</div>
{% endblock content %}

ForumQA/forum_qa/user/templates/user/register.html
{% extends 'question/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Se inscreva em nosso site!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Enviar inscrição</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Já possui uma conta? <a class="ml-2" href="{% url 'login' %}">Entrar</a>
            </small>
        </div>
    </div>
{% endblock content %}

ForumQA/forum_qa/user/templates/user/user_confirm_delete.html
{% extends "question/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <h2>Deseja mesmo excluir sua conta? Todas as perguntas e respostas postadas por você também serão excluídas.
            </h2>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">
                    Sim
                </button>
                <a class="btn btn-outline-secondary" href="{% url 'user-detail' request.user.id %}">
                    Não, cancelar
                </a>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}